---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pcf-pod-adm-binding
  namespace: pcf
subjects:
- kind: ServiceAccount
  name: pcf
roleRef:
  kind: Role
  name: pcf-pod-mgr
  apiGroup: rbac.authorization.k8s.io

