---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: tng-sta-registry-ca-install
  namespace: kube-system
  labels:
    k8s-app: registry-ca
spec:
  template:
    metadata:
      labels:
        name: registry-ca
    spec:
      containers:
      - name: registry-ca
        image: busybox
        command: [ 'sh' ]
        args: [ '-c', 'mkdir -p /etc/docker/certs.d/172.31.8.178:5000 && cp /home/core/registry-ca /etc/docker/certs.d/172.31.8.178:5000/ca.crt && exec tail -f /dev/null' ]
        volumeMounts:
        - name: etc-docker
          mountPath: /etc/docker/
        - name: ca-cert
          mountPath: /home/core
      terminationGracePeriodSeconds: 30
      volumes:
      - name: etc-docker
        hostPath:
          path: "/etc/docker/"
          type: "Directory"
      - name: ca-cert
        secret:
          secretName: tng-sta-registry-ca


