---
apiVersion: batch/v1
kind: Job
metadata:
  name: pcf5g-postgresql-init
spec:
  template:
    metadata:
      labels:
        app: pcf5g-postgresql-init
    spec:
      containers:
        - name: pcf5g-postgresql-init
          envFrom:
          image: 172.31.8.178:5000/pcf_5g-postgresql-init:latest
          imagePullPolicy: Always
      restartPolicy: OnFailure

